steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/cicd-448406/cloud-run-source-deploy/cicdproject/cicdproject:latest",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/cicd-448406/cloud-run-source-deploy/cicdproject/cicdproject:latest",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "my-image",
        "--image",
        "us-central1-docker.pkg.dev/cicd-448406/cloud-run-source-deploy/cicdproject/cicdproject:latest",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--ingress",
        "all",
        "--region",
        "asia-northeast1",
        "--project",
        "cicd-448406",
        "--quiet"
      ]

  # bucket
logsBucket: "sample_bucket_cicd"
serviceAccount: "projects/cicd-448406/serviceAccounts/649765672039-compute@developer.gserviceaccount.com"
options:
  logging: GCS_ONLY